<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%categories}}".
 *
 * @property integer $id
 * @property string $name
 *
 * @property Articles[] $articles
 */
class Categories extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%categories}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'slug'], 'required'],
            [['name', 'slug'], 'string', 'max' => 255],
            [['name', 'slug'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'نام',
            'slug' => 'مسیر ',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticles()
    {
        return $this->hasMany(Articles::className(), ['category_id' => 'id']);
    }

    public function beforeSave($insert) {
        $slug = preg_replace('/ /', '-', $this->slug);
        $slug = preg_replace('/-{1,}/', '-', $slug);
        $slug = preg_replace('/(^-|-$)/', '', $slug);
        $this->slug = $slug;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
